# Other configuration
## CORS Origin
quarkus.http.cors.origins=*
## Logs level
quarkus.log.level=INFO
quarkus.log.category."io.quarkus".level=INFO
#################################################################

# Database configuration
## Url de la base de datos en formato jdbc:postgresql://<IP o DNS>:5432/rego40
quarkus.datasource.jdbc.url=jdbc:postgresql://host.docker.internal:5432/indaga
## Usuario de postgres
quarkus.datasource.username=indaga
## Contraseña de postgres
quarkus.datasource.password=${INDAGA_POSTGRES_PASSWORD}
#################################################################

# FlyApp integration info
flythings.baseurl=${INDAGA_SERVICE_DNS}
## FlyApp General
quarkus.application.name=indaga-auth
flyapp.sdk.quarkus.base-href=/auth/
#####
## Url con DNS del servicio web (http://<IP o DNS>:8080)
flyapp.oauth.web-url=${flythings.baseurl}/auth
## Url con DNS del api (http://<IP o DNS>:8080/api)
flyapp.oauth.back-url=${flythings.baseurl}/auth/api
#####
flyapp.oauth.config.disable-sign-up=false
#################################################################

# S3 Properties
## Url de minio
s3.minio.endpoint=http://host.docker.internal:9090/
## Nombre del directorio donde se almacenarán los pocos ficheros que se guardan
s3.bucket.name=indaga-data
## Usuario de minio
s3.minio.key=indaga
## Contraseña de minio
s3.minio.secret=${INDAGA_MINIO_PASSWORD}
#################################################################

# Indaga Resources config
## Directorio donde se irán a buscar ficheros de recursos
flythings.resources.prefix=config/
#################################################################

# Properties to generate FlyApps token
## Fecha en timestamp unica para generar tokens unicos (flyapps.token.date=1758903501)
flyapps.token.date=1758903501
## Identificador único de token de seguridad (flyapps.token.jti=flythings.stack.auth)
flyapps.token.jti=flythings.stack.auth
# ID Token Alghiritm
flythings.oidc.sig=${FLYTHINGS_JWT_SIGN_KEY}
#################################################################

# Mail properties
## Url del servidor de correos
quarkus.mailer.host=ignore
## Usuario de acceso al servidor de correos
quarkus.mailer.username=ignore
## Contraseña de acceso al servidor de correos
quarkus.mailer.password=ignore
## Remitente de los email
quarkus.mailer.from=ignore
mailer.welcome.redirect-url=${flyapp.oauth.web-url}
mailer.reset-password.redirect-url=${flyapp.oauth.web-url}
#################################################################