# Database configuration
## Url de la base de datos en formato jdbc:postgresql://<IP o DNS>:5432/rego40
quarkus.datasource.jdbc.url=jdbc:postgresql://host.docker.internal:5432/indaga
## Usuario de postgres
quarkus.datasource.username=indaga
## Contraseña de postgres
quarkus.datasource.password=${INDAGA_POSTGRES_PASSWORD}
#################################################################

# S3 Properties
## Url de minio
s3.minio.endpoint=http://host.docker.internal:9090
## Nombre del directorio donde se almacenarán los pocos ficheros que se guardan/                  
s3.bucket.name=flythings-data
## Usuario de minio     
s3.minio.key=flythings
## Contraseña de minio
s3.minio.secret=${INDAGA_MINIO_PASSWORD}
#################################################################

# Flyapp integration info
flythings.baseurl=${INDAGA_SERVICE_DNS}
## FlyApp General
quarkus.application.name=flythings-dataspace-connector
# flyapp.sdk.quarkus.logo-url=https://app.flythings.io/v3/assets/images/logo/flythings.png
flyapp.sdk.quarkus.base-href=/connector/
######
## Url con DNS del servicio web (http://<IP o DNS>:8084)
flyapp.sdk.quarkus.web-url=${flythings.baseurl}/connector
## Url con DNS del api (http://<IP o DNS>:8084/api)
flyapp.sdk.quarkus.back-url=${flythings.baseurl}/connector/api
######
## Url con DNS del servicio web del módulo de auth (http://<IP o DNS>:8080)
flyapp.sdk.quarkus.oauth.web-url=${flythings.baseurl}/auth
## Url con DNS del api del módulo de auth (http://<IP o DNS>:8080/api)
flyapp.sdk.quarkus.oauth.back-url=${flythings.baseurl}/auth/api
######
## Token extraido de Acerca de la aplicación en el módulo de auth
oauth-api.flyapp.token=${FLYTHINGS_AUTH_TOKEN}
#################################################################

# Mail properties
## Url del servidor de correos
quarkus.mailer.host=ignore
## Usuario de acceso al servidor de correos
quarkus.mailer.username=ignore
## Contraseña de acceso al servidor de correos
quarkus.mailer.password=ignore
## Remitente de los email
quarkus.mailer.from=ignore
#################################################################
connector.url=${flyapp.sdk.quarkus.back-url}